on:
  push:
    branches:
      - master
      
jobs:
  build:
    runs-on: Ubuntu-latest
    steps:
      - name: "dhughugi"
        run: pwd
      
      
      - name: "dhughugi"
        run: echo Nada
      
      
